version: "3.9"

services:
  wine-api:
    build: .
    container_name: wine_api
    ports:
      - "8080:8080"
    volumes:
      - .:/app   # Mount local directory for live code changes
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload